name: Awesome Lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  awesome-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run awesome-lint
        run: npx awesome-lint
